name: Lint GitHub Actions workflows
on:
  workflow_dispatch:
#  pull_request:
#    paths:
#    - '.github/**'
#  merge_group:
#  push:
#    paths:
#    - '.github/**'

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v5
=======
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
>>>>>>> v2.3.0
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: SHELLCHECK_OPTS="-S error" ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
